// Module registry — barcha modullarni shu yerda ro'yxatga olamiz.
// Yangi modul qo'shish: src/modules/X.module.ts → bu yerda import + ALL_MODULES'ga qo'shish.

import {
  countriesModule,
  regionsModule,
  citiesModule,
  languagesModule,
  positionsModule,
  specialitiesModule,
  universitiesModule,
  organizationsModule,
  organizationExtraModule,
  schedulesModule,
  workDaysModule,
  holidaysModule,
  quotesModule,
  quoteRandomModule,
  organizationServicesModule,
  enumsModule,
  learningCentersModule,
  contractTypesModule,
  contractAdditionalTypesModule,
  commandTypesModule,
  vacancyApproveModule,
  structureTreeModule,
  reportsModule,
  exportModule,
} from '@/modules/structure.modules';
import {
  adminUsersModule,
  adminRolesModule,
  adminPermissionsModule,
} from '@/modules/admin.modules';
import { authModule, userModule } from '@/modules/auth.modules';
import {
  nationalitiesModule,
  departmentsModule,
  departmentPositionsModule,
  departmentExtrasModule,
  hrEnumsModule,
  workersModule,
  workerPositionsModule,
  workerPhonesModule,
  workerDisabilitiesModule,
  workerSickLeavesModule,
  workerPartiesModule,
  workerMilitariesModule,
  workerAcademicDegreesModule,
  workerAcademicTitlesModule,
  workerLanguagesModule,
  workerRelativesModule,
  workerOldCareersModule,
  workerPassportsModule,
  contractsModule,
  commandsModule,
  contractAdditionalModule,
  confirmationWorkersModule,
  vacanciesModule,
  vacationsModule,
  vacationSchedulesModule,
  polyclinicsModule,
  pensionersModule,
  leadersModule,
  organizationDocumentsModule,
  workerUniversitiesModule,
  incentivesModule,
  disciplinariesModule,
  businessTripsModule,
  workerExportColumnsModule,
  vacationScheduleYearsModule,
  exportTasksModule,
  filtersModule,
  workerRelativeDisabilitiesModule,
  enumsExtrasModule,
  vacationExtrasModule,
  workerAdditionalModule,
  sortableAliasesModule,
  filterExtrasModule,
  dashboardModule,
  dashboardViewsModule,
  workerPhotosModule,
  workerApplicationsModule,
  workerMedsModule,
  workerPositionExtrasModule,
  hrReportsModule,
  organizationPhonesModule,
  organizationPhonesListModule,
  workerUsersModule,
  eduPlansModule,
  departmentLocationsModule,
  vacancyPositionsModule,
} from '@/modules/hr.modules';
import {
  timesheetModule,
  timesheetWorkerDeptModule,
  timesheetWorkersModule,
  timesheetCheckWorkerModule,
  timesheetEnumsModule,
  timesheetDepartmentsModule,
  timesheetConfirmationsModule,
} from '@/modules/timesheet.modules';
import {
  turnstileBuildingsModule,
  turnstileTerminalsModule,
  turnstileOrgTerminalsModule,
  turnstileEnumsModule,
  turnstileWorkDurationModule,
  turnstileWorkerPhotosModule,
  turnstileAccessLevelsModule,
  turnstileHcpDevicesModule,
  turnstileHcpWorkersModule,
  turnstileEventsModule,
  turnstileSyncModule,
  turnstileTelegramModule,
  turnstileApproveAlModule,
  turnstileScheduleTypesModule,
  turnstileScheduleGroupsModule,
  turnstileWorkerSchedulesModule,
  turnstileScheduleStatsModule,
} from '@/modules/turnstile.modules';
import {
  examTopicsModule,
  examFiltersModule,
  examTopicFilesModule,
  examTopicExamsModule,
  examTopicExtrasModule,
  examCategoriesModule,
  examCategoryQuestionsModule,
  examWorkerExamsModule,
  examResultsModule,
  examEnumsModule,
  examPublicResultsModule,
} from '@/modules/exam.modules';
import {
  vacancyBoardModule,
  vacancyEnumsModule,
  vacancyAuthModule,
  vacancyCareersModule,
  vacancyEducationsModule,
  vacancyApplicationsModule,
  vacancyExamsModule,
  vacancyZoomModule,
} from '@/modules/vacancy.modules';
import {
  medWorkersModule,
  medSendedWorkersModule,
  medWorkerPositionsModule,
  medPensionersModule,
  medHospitalModule,
} from '@/modules/med.modules';
import {
  economistDashboardModule,
  economistUploadsModule,
  economistEnumsModule,
  economistStatementsModule,
  economistTaxFourModule,
  economistTaxFiveModule,
  economistPensionPaymentsModule,
  economistWorkerCategoriesModule,
  economistStaffingModule,
  economistTelegramModule,
} from '@/modules/economist.modules';
import type { ModuleDefinition } from '@/configs/types';

export const ALL_MODULES: ModuleDefinition[] = [
  // Auth + User
  authModule,
  userModule,
  // Structure
  countriesModule,
  regionsModule,
  citiesModule,
  languagesModule,
  positionsModule,
  specialitiesModule,
  universitiesModule,
  organizationsModule,
  organizationExtraModule,
  schedulesModule,
  workDaysModule,
  holidaysModule,
  quotesModule,
  quoteRandomModule,
  organizationServicesModule,
  enumsModule,
  learningCentersModule,
  contractTypesModule,
  contractAdditionalTypesModule,
  commandTypesModule,
  vacancyApproveModule,
  structureTreeModule,
  reportsModule,
  exportModule,
  // Admin
  adminUsersModule,
  adminRolesModule,
  adminPermissionsModule,
  // HR — Bosqich 1 (Foundation)
  nationalitiesModule,
  departmentsModule,
  departmentPositionsModule,
  departmentExtrasModule,
  hrEnumsModule,
  // HR — Bosqich 2 (Workers core)
  workersModule,
  workerPositionsModule,
  // HR — Bosqich 3 (Worker sub-resources)
  workerPhonesModule,
  workerDisabilitiesModule,
  workerSickLeavesModule,
  workerPartiesModule,
  workerMilitariesModule,
  workerAcademicDegreesModule,
  workerAcademicTitlesModule,
  workerLanguagesModule,
  workerRelativesModule,
  workerOldCareersModule,
  workerPassportsModule,
  // HR — Bosqich 4 (Contracts + Commands)
  contractsModule,
  commandsModule,
  contractAdditionalModule,
  confirmationWorkersModule,
  // HR — Bosqich 5 (Vacancies)
  vacanciesModule,
  // HR — Bosqich 6 (Vacations)
  vacationsModule,
  vacationSchedulesModule,
  vacationScheduleYearsModule,
  // HR — Bosqich 7 (Dashboard + Other)
  polyclinicsModule,
  pensionersModule,
  leadersModule,
  organizationDocumentsModule,
  workerUniversitiesModule,
  incentivesModule,
  disciplinariesModule,
  businessTripsModule,
  // HR — Bosqich 8 (HR Exports)
  workerExportColumnsModule,
  exportTasksModule,
  filtersModule,
  // HR — Worker Relative Disabilities (apiResource, Laravel-bug)
  workerRelativeDisabilitiesModule,
  // HR — Enum extras + Filter extras + Worker-additional + Vacation extras + Sortable aliases
  enumsExtrasModule,
  vacationExtrasModule,
  workerAdditionalModule,
  sortableAliasesModule,
  filterExtrasModule,
  // HR — Dashboard + Dashboard Views
  dashboardModule,
  dashboardViewsModule,
  // HR — Worker Photos + Applications + Meds + WorkerPosition extras + Reports
  workerPhotosModule,
  workerApplicationsModule,
  workerMedsModule,
  workerPositionExtrasModule,
  hrReportsModule,
  // Phase 3C
  organizationPhonesModule,
  organizationPhonesListModule,
  workerUsersModule,
  eduPlansModule,
  departmentLocationsModule,
  vacancyPositionsModule,
  // TimeSheet — Bosqich 9
  timesheetModule,
  timesheetWorkerDeptModule,
  timesheetWorkersModule,
  timesheetCheckWorkerModule,
  timesheetEnumsModule,
  timesheetDepartmentsModule,
  timesheetConfirmationsModule,
  // Turnstile — Bosqich 10 (17 sub-modules)
  turnstileBuildingsModule,
  turnstileTerminalsModule,
  turnstileOrgTerminalsModule,
  turnstileEnumsModule,
  turnstileWorkDurationModule,
  turnstileWorkerPhotosModule,
  turnstileAccessLevelsModule,
  turnstileHcpDevicesModule,
  turnstileHcpWorkersModule,
  turnstileEventsModule,
  turnstileSyncModule,
  turnstileTelegramModule,
  turnstileApproveAlModule,
  turnstileScheduleTypesModule,
  turnstileScheduleGroupsModule,
  turnstileWorkerSchedulesModule,
  turnstileScheduleStatsModule,
  // Exam — Bosqich 11 (11 sub-modules)
  examTopicsModule,
  examFiltersModule,
  examTopicFilesModule,
  examTopicExamsModule,
  examTopicExtrasModule,
  examCategoriesModule,
  examCategoryQuestionsModule,
  examWorkerExamsModule,
  examResultsModule,
  examEnumsModule,
  examPublicResultsModule,
  // Vacancy — 8 sub-modul
  vacancyBoardModule,
  vacancyEnumsModule,
  vacancyAuthModule,
  vacancyCareersModule,
  vacancyEducationsModule,
  vacancyApplicationsModule,
  vacancyExamsModule,
  vacancyZoomModule,
  // Med — 5 sub-modul
  medWorkersModule,
  medSendedWorkersModule,
  medWorkerPositionsModule,
  medPensionersModule,
  medHospitalModule,
  // Economist — 10 sub-modul
  economistDashboardModule,
  economistUploadsModule,
  economistEnumsModule,
  economistStatementsModule,
  economistTaxFourModule,
  economistTaxFiveModule,
  economistPensionPaymentsModule,
  economistWorkerCategoriesModule,
  economistStaffingModule,
  economistTelegramModule,
];
